spring.application.name=TaxEase
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/taxease
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
jwt.secret=your_very_long_and_secure_random_string_here
spring.jpa.show-sql=true