spring.application.name=TaxEase
server.port=8081
jwt.secret=djdjdjddjfmfjfjfjfjfjfjfjfjfjfjfjffjfjfjfjsksksks


spring.datasource.url=jdbc:mysql://localhost:3306/taxease
spring.datasource.username=root
spring.datasource.password=Harshith@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
